name: Cachix

on:
  push:
    branches:
      - main

jobs:
  cachix:
    name: Cachix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Install jq
        run: nix profile install --inputs-from . nixpkgs#jq

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: sugar
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          installCommand: nix profile install nixpkgs#cachix

      - name: Push Flake Inputs
        run: nix flake archive --json | jq -r '.path , (.inputs | to_entries[].value.path)' | cachix push sugar

      - name: Push Flake Outputs
        run: |
          for package in $(find packages -mindepth 1 -maxdepth 1 -type d -exec basename {} \;); do
            nix build ".#sugar.${package}" --json | jq -r '.[].outputs | to_entries[].value' | cachix push sugar
          done
